/** Adapt the pinned generator's date storage without changing adapter properties. */
export function normalizeAuthSchema(source: string): string {
  const tables = [...source.matchAll(/pgTable\(\s*["'](\w+)["']/g)]
    .map((match) => match[1]).sort();
  if (tables.join(",") !== "account,rate_limit,session,user,verification") {
    throw new Error("Auth generator returned an unexpected table set; review before continuing.");
  }

  let result = source.replace(
    /timestamp\((["'])([a-z_]+)\1\)/g,
    'timestamp("$2", { withTimezone: true })',
  );
  result = result.replace(
    /(updatedAt:\s*timestamp\([^\n)]*\))(?!\s*\.defaultNow\()/g,
    "$1.defaultNow()",
  );
  if (/timestamp\((?!"[a-z_]+", \{ withTimezone: true \}\))/.test(result) || !result.includes("withTimezone: true")) {
    throw new Error("Auth generator returned unexpected date syntax; review before continuing.");
  }
  return "// Generated by auth@1.6.33; timestamp/default adjustments: npm run auth:generate.\n" + result;
}
